name: format project

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup nix & cachix
        uses: ./.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: run cargo fmt
        run: |
          nix build -L .#checks.x86_64-linux.fmt

  nix-fmt:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: setup nix & cachix
        uses: ./.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix fmt

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: fmt nix files"
