name: lint project

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        check: [teawiebot, clippy]

    steps:
      - uses: actions/checkout@v3

      - name: setup nix & cachix
        uses: ./.github/actions/setup-nix
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: lint
        run: |
          nix build -L .#checks.x86_64-linux.${{ matrix.check }}
